export const FETCHING_WORLD_DATA = "FETCHING_WORLD_DATA";
export const FETCHED_WORLD_DATA = "FETCHED_WORLD_DATA";

export const FETCHING_COUNTRY_DATA = "FETCHING_COUNTRY_DATA";
export const FETCHED_COUNTRY_DATA = "FETCHED_COUNTRY_DATA";
export const FETCHING_COUNTRY_DATA_ERROR = "FETCHING_COUNTRY_DATA_ERROR";

export const FETCHING_ERROR = "FETCHING_ERROR";
